/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.FileController;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.FileMessage;
import util.FileUtil;

/**
 *
 * @author boli6
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelListar = new javax.swing.JPanel();
        jButtonListarArquivos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListListarArquivos = new javax.swing.JList<>();
        jPanelEnviar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCaminhoArquivo = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jPanelBaixar = new javax.swing.JPanel();
        jButtonBaixar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNomeArquivo = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonListarArquivos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonListarArquivos.setText("Listar Arquivos");
        jButtonListarArquivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarArquivosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Arquivos Disponíveis no Servidor:");

        jListListarArquivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListListarArquivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListListarArquivos);

        javax.swing.GroupLayout jPanelListarLayout = new javax.swing.GroupLayout(jPanelListar);
        jPanelListar.setLayout(jPanelListarLayout);
        jPanelListarLayout.setHorizontalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelListarLayout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jButtonListarArquivos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelListarLayout.setVerticalGroup(
            jPanelListarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListarLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButtonListarArquivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar", jPanelListar);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Enviar Arquvio Para o Servidor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Caminho do Arquivo:");

        jTextFieldCaminhoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaminhoArquivoActionPerformed(evt);
            }
        });

        jButtonEnviar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEnviarLayout = new javax.swing.GroupLayout(jPanelEnviar);
        jPanelEnviar.setLayout(jPanelEnviarLayout);
        jPanelEnviarLayout.setHorizontalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnviarLayout.createSequentialGroup()
                .addGroup(jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEnviarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCaminhoArquivo)
                            .addComponent(jButtonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)))
                    .addGroup(jPanelEnviarLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelEnviarLayout.setVerticalGroup(
            jPanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEnviarLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCaminhoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enviar", jPanelEnviar);

        jButtonBaixar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonBaixar.setText("Baixar");
        jButtonBaixar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBaixarMouseClicked(evt);
            }
        });
        jButtonBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaixarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Baixar Arquivo do Servidor");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nome do Arquivo:");

        jTextFieldNomeArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBaixarLayout = new javax.swing.GroupLayout(jPanelBaixar);
        jPanelBaixar.setLayout(jPanelBaixarLayout);
        jPanelBaixarLayout.setHorizontalGroup(
            jPanelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaixarLayout.createSequentialGroup()
                .addGroup(jPanelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaixarLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldNomeArquivo)
                            .addComponent(jButtonBaixar, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)))
                    .addGroup(jPanelBaixarLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel4)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanelBaixarLayout.setVerticalGroup(
            jPanelBaixarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaixarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Baixar", jPanelBaixar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarArquivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarArquivosActionPerformed
        try {
            FileMessage req = new FileMessage();
            req.cmd = "list_req";

            FileMessage resp = FileController.enviarComando(req);

            // cria o modelo da jlist
            DefaultListModel<String> model = new DefaultListModel<>();

            if (resp.files != null) {
                for (String nome : resp.files) {
                    model.addElement(nome); // add cada nome de arquivo ao modelo
                }
            }

            jListListarArquivos.setModel(model); // aplica o modelo na lista
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao listar arquivos: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonListarArquivosActionPerformed

    private void jListListarArquivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListListarArquivosMouseClicked
        String arquivoSelecionado = jListListarArquivos.getSelectedValue();
        jTextFieldNomeArquivo.setText(arquivoSelecionado); // já preenche para o download
    }//GEN-LAST:event_jListListarArquivosMouseClicked

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        try {
            String nome = jTextFieldCaminhoArquivo.getText().trim();
            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o nome do arquivo.");
                return;
            }

            String caminho = "cliente/arquivos/" + nome;
            File file = new File(caminho);
            if (!file.exists()) {
                JOptionPane.showMessageDialog(this, "Arquivo não encontrado em: " + caminho);
                return;
            }

            FileMessage req = new FileMessage();
            req.cmd = "put_req";
            req.file = nome; // só o nome, não o caminho
            req.value = FileUtil.fileToBase64(caminho);
            req.hash = FileUtil.hashFile(caminho);

            FileMessage resp = FileController.enviarComando(req);
            JOptionPane.showMessageDialog(this, "Status: " + resp.status);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jTextFieldCaminhoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaminhoArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaminhoArquivoActionPerformed

    private void jTextFieldNomeArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeArquivoActionPerformed

    private void jButtonBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaixarActionPerformed
        try {
            String nome = jTextFieldNomeArquivo.getText().trim();
            if (nome.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o nome do arquivo.");
                return;
            }

            FileMessage req = new FileMessage();
            req.cmd = "get_req";
            req.file = nome;

            FileMessage resp = FileController.enviarComando(req);
            if (resp.value == null || resp.value.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Arquivo não encontrado.");
                return;
            }

            File pasta = new File("cliente/arquivos");
            pasta.mkdirs(); // cria pasta se não existir

            String caminho = "cliente/arquivos/" + nome;
            FileUtil.base64ToFile(resp.value, caminho);
            JOptionPane.showMessageDialog(this, "Arquivo salvo em: " + caminho);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao baixar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonBaixarActionPerformed

    private void jButtonBaixarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBaixarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBaixarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBaixar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonListarArquivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jListListarArquivos;
    private javax.swing.JPanel jPanelBaixar;
    private javax.swing.JPanel jPanelEnviar;
    private javax.swing.JPanel jPanelListar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldCaminhoArquivo;
    private javax.swing.JTextField jTextFieldNomeArquivo;
    // End of variables declaration//GEN-END:variables
}
